export * from './hero'
export * from './Introduction'
export * from './Rule'
export * from './criteria'
export * from './rewards'
export * from './partners'
export * from './privacyPolicy'
export * from './TailwindTimeline'
export * from "./TimeLineThree"
export * from "./Header"